import {defineConfig} from 'vite';
import tailwindcss from '@tailwindcss/vite';
import fs from 'fs';
import path from 'path';

function serveAndCopyAssetsPlugin() {
  // Helper to pre-bundle PHP tab templates and firebase-applet-config.json for offline/APK support
  function bundleTemplates() {
    const tabs = [
      { id: "tab-home", file: "src/dashboard_tabs/home.php" },
      { id: "tab-events", file: "src/dashboard_tabs/events_tab.php" },
      { id: "tab-tickets", file: "src/dashboard_tabs/tickets.php" },
      { id: "tab-wallet", file: "src/dashboard_tabs/user_balance.php" },
      { id: "tab-history", file: "src/dashboard_tabs/history.php" },
      { id: "tab-profile", file: "src/dashboard_tabs/profile.php" },
      { id: "tab-badge-request", file: "src/dashboard_tabs/badge_request.php" },
      { id: "tab-refer", file: "src/dashboard_tabs/share_earn.php" },
      { id: "tab-jackpot", file: "src/dashboard_tabs/jackpot.php" },
      { id: "tab-tasks", file: "src/dashboard_tabs/missions.php" },
      { id: "tab-otp", file: "src/dashboard_tabs/otp.php" },
      { id: "admin-tab-agent-leaders", file: "src/admin_tabs/agent_leaders.php" },
      { id: "admin-tab-subagents-list", file: "src/admin_tabs/subagents_admin.php" }
    ];

    const templates = {};
    for (const tab of tabs) {
      const fullPath = path.resolve(process.cwd(), tab.file);
      if (fs.existsSync(fullPath)) {
        templates[tab.id] = fs.readFileSync(fullPath, "utf-8");
      } else {
        console.warn(`Template file not found: ${fullPath}`);
      }
    }

    let firebaseConfig = null;
    const configPath = path.resolve(process.cwd(), "firebase-applet-config.json");
    if (fs.existsSync(configPath)) {
      try {
        firebaseConfig = JSON.parse(fs.readFileSync(configPath, "utf-8"));
      } catch (e) {
        console.warn("Could not parse firebase-applet-config.json for bundle");
      }
    }

    const jsContent = `// This file is auto-generated by Vite. Do not edit manually.
export const bundledTabs = ${JSON.stringify(templates, null, 2)};
export const fallbackFirebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)};
`;

    const destPath = path.resolve(process.cwd(), "src/js/bundledTabs.js");
    const destDir = path.dirname(destPath);
    if (!fs.existsSync(destDir)) {
      fs.mkdirSync(destDir, { recursive: true });
    }
    fs.writeFileSync(destPath, jsContent, "utf-8");
    console.log(`[Offline-Bundler] Successfully generated templates bundle at: ${destPath}`);
  }

  // Run immediately on load/build
  bundleTemplates();

  return {
    name: 'serve-and-copy-assets',
    buildStart() {
      bundleTemplates();
    },
    // 1. Dev mode: Serve .php files and config JSONs
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const decodedUrl = decodeURIComponent(req.url.split('?')[0]);
        // Resolve path relative to project root
        const filePath = path.join(process.cwd(), decodedUrl);
        
        // Only serve if the file exists and is a file
        if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
          const ext = path.extname(filePath);
          if (ext === '.php' || ext === '.json' || decodedUrl.endsWith('firebase-applet-config.json')) {
            let contentType = 'text/plain';
            if (ext === '.php') {
              contentType = 'text/html';
            } else if (ext === '.json') {
              contentType = 'application/json';
            }
            res.setHeader('Content-Type', contentType);
            res.end(fs.readFileSync(filePath));
            return;
          }
        }
        next();
      });
    },
    // 2. Build mode: Copy .php and root config JSON to dist folder
    closeBundle() {
      const distDir = path.resolve(process.cwd(), 'dist');
      if (!fs.existsSync(distDir)) return;

      // Copy firebase-applet-config.json to dist
      const srcConfig = path.resolve(process.cwd(), 'firebase-applet-config.json');
      const destConfig = path.resolve(distDir, 'firebase-applet-config.json');
      if (fs.existsSync(srcConfig)) {
        fs.copyFileSync(srcConfig, destConfig);
        console.log('Copied firebase-applet-config.json to dist/');
      }

      // Copy other JSON config if exists
      const srcBlueprint = path.resolve(process.cwd(), 'firebase-blueprint.json');
      const destBlueprint = path.resolve(distDir, 'firebase-blueprint.json');
      if (fs.existsSync(srcBlueprint)) {
        fs.copyFileSync(srcBlueprint, destBlueprint);
      }

      // Recursively find and copy all .php files from src to dist/src
      const srcDir = path.resolve(process.cwd(), 'src');
      const destSrcDir = path.resolve(distDir, 'src');

      function copyRecursive(src, dest) {
        if (!fs.existsSync(src)) return;
        const stats = fs.statSync(src);
        if (stats.isDirectory()) {
          if (!fs.existsSync(dest)) {
            fs.mkdirSync(dest, { recursive: true });
          }
          const files = fs.readdirSync(src);
          for (const file of files) {
            copyRecursive(path.join(src, file), path.join(dest, file));
          }
        } else if (stats.isFile()) {
          const ext = path.extname(src);
          if (ext === '.php' || ext === '.js' || ext === '.css') {
            const destDir = path.dirname(dest);
            if (!fs.existsSync(destDir)) {
              fs.mkdirSync(destDir, { recursive: true });
            }
            fs.copyFileSync(src, dest);
          }
        }
      }

      copyRecursive(srcDir, destSrcDir);
      console.log('Copied .php and other tab assets from src/ to dist/src/');
    }
  };
}

export default defineConfig(() => {
  return {
    base: "./",
    plugins: [
      tailwindcss(),
      serveAndCopyAssetsPlugin()
    ],
    server: {
      hmr: false,
      port: 3000,
      host: '0.0.0.0'
    },
  };
});

